FROM python:3.12-slim

COPY t/openresty-integration/tests/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /tests
COPY t/openresty-integration/tests/ /tests/
COPY t/integration/certs/ /certs/

CMD ["pytest", "-v", "--tb=short", "/tests/"]
